In [7]:
#Importar Librerias

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from pandas.core.common import random_state
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [43]:
#Importar el Dataset

dataset = np.load("/Users/diegoalvarez/Documents/Maestria/Python/Proyecto/proyecto_training_data.npy")

SalePrice = dataset[:, 0]
OverallQual = dataset[:, 1]
FstFlrSF = dataset[:, 2]
TotRmsAbvGrd = dataset[:, 3]
YearBuilt = dataset[:, 4]
LotFrontage = dataset[:, 5]

In [44]:
print(SalePrice)
print(OverallQual)
print(FstFlrSF)
print(TotRmsAbvGrd)
print(YearBuilt)
print(LotFrontage)

[208500. 181500. 223500. ... 266500. 142125. 147500.]
[7. 6. 7. ... 7. 5. 5.]
[ 856. 1262.  920. ... 1188. 1078. 1256.]
[8. 6. 6. ... 9. 5. 6.]
[2003. 1976. 2001. ... 1941. 1950. 1965.]
[65. 80. 68. ... 66. 68. 75.]


In [46]:
tamano_total = len(dataset)
porcentaje_entrenamiento = 0.8

#Calcular el índice para dividir datos
indice_div = int(tamano_total * porcentaje_entrenamiento)

#Dividir los datos en conjunto de entrenamiento y testing
datos_entren = dataset[:indice_div, :]
datos_val = dataset[indice_div:, :]

In [47]:
print("Dimensiones del conjunto de entrenamiento:", datos_entren.shape)
print("Dimensiones del conjunto de validación/pruebas:", datos_val.shape)

Dimensiones del conjunto de entrenamiento: (1168, 6)
Dimensiones del conjunto de validación/pruebas: (292, 6)
